"""
Django settings for PicturesDjango project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
import logging
from pathlib import Path
from decouple import config
# for translations, from https://www.codementor.io/@curiouslearner/supporting-multiple-languages-in-django-part-1-11xjd2ovik
from django.utils.translation import gettext_lazy as _

# === Early logging setup for debugging settings loading ===
# This will print to the console even during `manage.py` commands.
logging.basicConfig(
    level=logging.INFO,
    format='[SETTINGS-DEBUG] %(message)s',
    stream=sys.stdout,
    force=True   # override any previous basicConfig
)
logger = logging.getLogger('settings_debug')
logger.info("===== SETTINGS.PY LOADING START =====")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Root directory for the jpegs
IMAGES_PATH = config('IMAGES_PATH', default='/home/mehdi/Images')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# For local use only, you can leave it empty and a fallback will be generated.
# Best practice: put SECRET_KEY in your .env file.
SECRET_KEY = config('SECRET_KEY', default=None)

if not SECRET_KEY:
    # Fallback for pure local use (not ideal if you ever share the machine image,
    # but avoids forcing you to manage a secret for an internal-only app).
    import hashlib
    SECRET_KEY = hashlib.sha256(
        (str(IMAGES_PATH) + "picturesdjango-local-fallback").encode()
    ).hexdigest()

# SECURITY WARNING: don't run with debug turned on in production!
#
# Strong priority to real environment variable (for one-shot usage like
# DEBUG=True python manage.py runserver or migrate), falling back to .env / decouple.
DEBUG = os.environ.get('DEBUG', '').lower() in ('true', '1', 'yes') or config('DEBUG', default=False, cast=bool)

logger.info(f"DEBUG after evaluation = {DEBUG} | os.environ.get('DEBUG') = {os.environ.get('DEBUG')!r}")

# Flag pour détecter si on est en mode test (python manage.py test ...)
# Utile pour assouplir certains contrôles stricts (ex: Path.resolve(strict=True))
# pendant les tests tout en les gardant actifs en utilisation réelle.
TESTING = 'test' in sys.argv

#Mehdi: the second IP is the Tailscape vpn one (https://login.tailscale.com/), it allows to connect to the laptop at home on wifi from everywhere
#and the third the https tailscape one
ALLOWED_HOSTS = ["127.0.0.1", "100.70.189.84", "mehdi-thinkbook-13s-g2-itl.taila97662.ts.net"]

# HTTPS via tailscale serve (TLS terminé en amont, Django reçoit du HTTP local).
CSRF_TRUSTED_ORIGINS = [
    "https://mehdi-thinkbook-13s-g2-itl.taila97662.ts.net",
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'PicturesApp',
]

# Django Debug Toolbar
# We add the app (so its migrations are visible to `migrate`) only when DEBUG=True
# and the package is installed via requirements-dev.txt.
if DEBUG:
    try:
        import debug_toolbar
        INSTALLED_APPS.append('debug_toolbar')
        logger.info(">>> debug_toolbar successfully ADDED to INSTALLED_APPS")
    except ImportError:
        logger.info(">>> debug_toolbar package NOT FOUND (ImportError)")
else:
    logger.info(">>> DEBUG=False → debug_toolbar NOT added to INSTALLED_APPS (skipped)")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',#to serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',#LocaleMiddleware is responsible for determining the user's language preference based on various factors like the URL prefix, cookies, or the Accept-Language header from the browser
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'PicturesDjango.middleware.ReadOnlyRemoteMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'PicturesDjango.middleware.ShortHtmlCacheMiddleware',
]

# Browser cache TTL for HTML pages (seconds). 0 disables the header.
HTML_PAGE_CACHE_SECONDS = 30

# Rate limit for gallery previews (big only) per browser session. 0 disables.
# view thumbnails (series cards, folders) are not limited.
IMAGE_RATE_LIMIT_BIG_VIEW = 20
IMAGE_RATE_LIMIT_WINDOW = 5

# Read-only mode for remote access (HTTPS / Tailscale). Writable only on these hosts.
WRITABLE_HOSTS = ["127.0.0.1", "localhost"]
READONLY_SAFE_POST_URL_NAMES = ["search_form"]
# Remote hosts may only resolve these url names (gallery read-only surface).
READONLY_ALLOWED_URL_NAMES = [
    "home",
    "DisplaySecondLevel",
    "DisplayThirdLevel",
    "photo_Jpeg",
    "photoDetail",
    "ContactsSheet",
    "photo_gallery",
    "ContactsSheetBySearch",
    "subjectsBySearch",
    "photo_galleryBySearch",
    "search_form",
]

# Django Debug Toolbar middleware (must be early, only in DEBUG)
if DEBUG and 'debug_toolbar' in INSTALLED_APPS:
    MIDDLEWARE.insert(1, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    logger.info(">>> debug_toolbar middleware INSERTED into MIDDLEWARE")
else:
    logger.info(f">>> debug_toolbar middleware NOT inserted (DEBUG={DEBUG}, in INSTALLED_APPS={'debug_toolbar' in INSTALLED_APPS})")

# Django Debug Toolbar configuration (memory store + large contact sheets)
if DEBUG and 'debug_toolbar' in INSTALLED_APPS:
    DEBUG_TOOLBAR_CONFIG = {
        'RESULTS_STORE': 'debug_toolbar.storage.CacheStore',   # ← on repasse en cache
        'RESULTS_CACHE_SIZE': 2000,                             # beaucoup plus permissif
        'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
        'SQL_WARNING_THRESHOLD': 200,
    }
    logger.info(">>> DEBUG_TOOLBAR_CONFIG activated with CacheStore (RESULTS_CACHE_SIZE=200)")
else:
    logger.info(">>> DEBUG_TOOLBAR_CONFIG NOT activated")

ROOT_URLCONF = 'PicturesDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'PicturesDjango.context_processors.writable_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'PicturesDjango.wsgi.application'

logger.info("===== SETTINGS.PY LOADING FINISHED =====")


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        #far easier for updates between machine and backups to have the db describing the images next to the images
        'NAME': os.path.join(IMAGES_PATH,'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Provide a lists of languages which your site supports.
LANGUAGES = (
    ('en', _('English')),
    ('fr', _('Français')),
)

# translations are generated from marked labels by running this
# django-admin makemessages -l fr
# Once translated manually in po file, please run django-admin compilemessages
# or new translations won't be taken into account
# see https://docs.djangoproject.com/en/3.0/topics/i18n/translation/

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# Set the default language for your site.
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery. Make sure it is set to
# True if you want to support localization
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = True

USE_TZ = True

# Contains the path list where Django should look into for django.po files for all supported languages
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# The URL to use when referring to static files (where they will be served from)
STATIC_URL = '/static/'

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# to serve static files not linked to an app-->CSS,...
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
