# Generated by Django 4.2.14 on 2024-08-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('boite', models.CharField(max_length=10)),
                ('rangee', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('sujet_dias', models.TextField()),
                ('agrandi', models.BooleanField()),
                ('classe', models.BooleanField()),
                ('verifie', models.BooleanField()),
                ('commentaire', models.TextField()),
                ('camera_digitale', models.BooleanField()),
                ('premier_niveau', models.CharField(max_length=100)),
                ('second_niveau', models.CharField(max_length=100)),
                ('troisieme_niveau', models.CharField(max_length=100)),
                ('nom_fichier_jpeg', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
