# Generated by Django 5.1 on 2024-08-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('sujet', models.CharField(db_index=True, max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('boite', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('rangee', models.IntegerField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('sujet_dias', models.TextField()),
                ('agrandi', models.BooleanField()),
                ('classe', models.BooleanField()),
                ('verifie', models.BooleanField()),
                ('commentaire', models.TextField()),
                ('camera_digitale', models.BooleanField(db_index=True)),
                ('premier_niveau', models.CharField(db_index=True, max_length=100)),
                ('second_niveau', models.CharField(max_length=100)),
                ('troisieme_niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_fichier_jpeg', models.CharField(blank=True, max_length=100, null=True)),
                ('pkey', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('checksum', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['premier_niveau', 'second_niveau', 'troisieme_niveau'], name='PicturesApp_premier_c58668_idx')],
            },
        ),
    ]
