# Generated by Django 5.1 on 2024-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicturesApp', '0002_alter_photomodel_boite_alter_photomodel_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='boite',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='camera_digitale',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='premier_niveau',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='sujet',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='photomodel',
            index=models.Index(fields=['premier_niveau', 'second_niveau', 'troisieme_niveau'], name='PicturesApp_premier_c58668_idx'),
        ),
    ]
