# Generated by Django 5.1 on 2024-08-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicturesApp', '0002_alter_photomodel_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
