# Generated by Django 5.1 on 2024-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicturesApp', '0003_alter_photomodel_boite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='id',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='pkey',
            field=models.AutoField(db_index=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
