# Generated by Django 6.0.5 on 2026-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicturesApp', '0004_add_technical_exif_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='lieu',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
