# Generated by Django 6.0.5 on 2026-05-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicturesApp', '0005_add_lieu_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='classe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='rangee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='sujet_dias',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='verifie',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
