# Generated by Django 6.0.5 on 2026-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicturesApp', '0006_alter_photomodel_classe_alter_photomodel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='highlight_clip_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='luminance_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='quality_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='shadow_clip_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
