# Generated by Django 6.0.5 on 2026-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicturesApp', '0007_add_photo_quality_exposure_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photomodel',
            index=models.Index(fields=['checksum', 'agrandi'], name='PicturesApp_checksu_7bd552_idx'),
        ),
        migrations.AddIndex(
            model_name='photomodel',
            index=models.Index(fields=['agrandi', 'premier_niveau'], name='PicturesApp_agrandi_f9126c_idx'),
        ),
    ]
