// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//
#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
#include <afxtempl.h>

#include "stdio.h"
#include "ctype.h"

#pragma warning(disable:4786)
#include "vector"
#include "set"
#include "string"
